### ISSUE TITLE
Can't figure out version bounds to use the package in a simple example

### ISSUE THREAD

**Issue by L7R7** [tek/polysemy-log#1]
I tried to put together a minimal stack project where I can try out polysemy-log to see how it feels. However, I can't figure out how to set the version bounds for different packages to make it work.

My code is here: https://github.com/L7R7/haskell-incubator/tree/main/logging

A few observations:
* I'm using the latest stackage lts resolver.
* Preferably, I'd like to use polysemy 1.5.0.0. However, I couldn't manage to get it working with any of the polysemy versions I tried
* I can get a step forward when I add `allow-newer: true` to my `stack.yaml`, but that's also something I don't really want to do

I'm running out of ideas for how to fix this. Am I missing something?

**Comment by tek** [comment]
please try `0.2.1.0`! that has polysemy 1.5

**Comment by tek** [comment]
ah and you'll also need co-log from master, since that has not been released for 1.5 yet.

**Comment by L7R7** [comment]
Oh thanks, I missed `0.2.1.0`!
I also included the latest master for `polysemy-conc` and `polysemy-time` and now I have a build error: 

```
polysemy-log   > configure
polysemy-log   > Configuring polysemy-log-0.2.1.0...
polysemy-log   > build
polysemy-log   > Preprocessing library for polysemy-log-0.2.1.0..
polysemy-log   > Building library for polysemy-log-0.2.1.0..
polysemy-log   > [ 1 of 15] Compiling Polysemy.Log.Prelude
polysemy-log   > [ 2 of 15] Compiling Prelude
polysemy-log   > [ 3 of 15] Compiling Polysemy.Log.Data.Severity
polysemy-log   > [ 4 of 15] Compiling Polysemy.Log.Data.LogMetadata
polysemy-log   > [ 5 of 15] Compiling Polysemy.Log.Data.LogMessage
polysemy-log   > [ 6 of 15] Compiling Polysemy.Log.Data.LogEntry
polysemy-log   > [ 7 of 15] Compiling Polysemy.Log.Format
polysemy-log   > 
polysemy-log   > /tmp/stack-084ae0ce01bcdcf8/polysemy-log-0.2.1.0/lib/Polysemy/Log/Format.hs:44:11: error:
polysemy-log   >     • Data.String.Interpolate.i: unescaped # symbol without interpolation brackets
polysemy-log   >     • In the quasi-quotation:
polysemy-log   >         [qt|#{shortModule (toText srcLocModule)}##{srcLocStartLine}|]
polysemy-log   >    |
polysemy-log   > 44 |       [qt|#{shortModule (toText srcLocModule)}##{srcLocStartLine}|]
polysemy-log   >    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
polysemy-log   > 
Progress 1/3

--  While building package polysemy-log-0.2.1.0 (scroll up to its section to see the error) using:
      /home/leo/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by tek** [comment]
ah yeah, I guess I should put version bounds on the string-interpolate dep, or remove it

**Comment by tek** [comment]
just fixed the bug with the unescaped hash and released!

**Comment by L7R7** [comment]
Thank you for the fast responses! I have something to work with now. I had to go back to a 16.x lts version of the stackage resolver because otherwise I have version conflicts with `aeson` (it requires 1.4.7.1, 17.x resolver brings 1.5.6.0). This is fine for me for now, as I just want to play around with the logging functionality.

I guess this issue can be closed now.

off-topic: For me it would have been helpful if the examples in the readme had a "full" working code including all the interpreters to run it in IO. I could prepare a PR with a proposal for it if you're interested in that (as soon as I'm comfortable with it)?

**Comment by tek** [comment]
added an example! `aeson` is a dep of `polysemy-time`, I'm currently updating it there. Appreciate your suggestions, thanks!

**Comment by tek** [comment]
fyi @L7R7 the newest version _should_ work with that aeson version now!
